### PR TITLE
Added metadata in createRenderContext function to support metablocks.

### PR DESCRIPTION
**Pull request by raymondbh**

### CODE REVIEW

**Comment by tterrag1098** [comment]
This is not necessary and will break backwards compat.

**Comment by raymondbh** [comment]
Ok? then how can I use metablocks? (I'm a little noob here, just trying to learn)

**Comment by tterrag1098** [comment]
Store the meta in your ISubmapManager. Chisel does this in pretty much all of its managers

**Comment by raymondbh** [comment]
I've probably done it all wrong then, but could you give me a hint?
https://github.com/raymondbh/TFC-Additions/blob/master/src/main/java/org/rbh/tfcadditions/Blocks/BlockDent.java
https://github.com/raymondbh/TFC-Additions/blob/master/src/main/java/org/rbh/tfcadditions/Api/SubmapManCTM.java

**Comment by tterrag1098** [comment]
Have one manager per metadata. Don't try to make one class do it all.

**Pull request closed without merging**
